default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: hey_jobs
  password: hey_jobs

development:
  <<: *default
  database: hey_jobs_development

test:
  <<: *default
  database: hey_jobs_test

production:
  <<: *default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV.fetch("DATABASE_NAME") { 'hey_jobs' } %>
  host: <%= ENV.fetch("DATABASE_HOST") { 'localhost' } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { 'hey_jobs' } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { 'hey_jobs' } %>
