# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 09ea595dc22558888e282f38ea37be49cc7530cc392b3ce0f19eb84a6070ede08a0f08ea58df1b3f021bbd3d31dc024b7eedc4c63e6224a4d696b74e490f4e1d

test:
  secret_key_base: c2b5a046651a5126db518954545bb92bc185db8ae198348b868ea25687c62ecc94b427b3b984f346ae4ec99473b12a46bf20f4694062e7709d0d5e3038b19d29

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
